'use client'

import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'
import Navbar from 'components/navbar/Navbar'
import Footer from 'components/footer/Footer'
import styled from '@emotion/styled'
import { usePathname } from 'next/navigation'

const SpaceGrotesk = Space_Grotesk({
	subsets: ['latin'],
	weight: ['400', '700']
})

const HTML = styled.html`
	scroll-behavior: smooth;
	button {
		font-family: ${SpaceGrotesk.style.fontFamily};
	}
`

const metadata: Metadata = {
	title: 'Elkod',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const path = usePathname()
	return (
		<HTML lang="en" className={SpaceGrotesk.className}>
			<head>
				<title>Elkod</title>
				<link rel="icon" href="/fa.ico" /> {/* Dodat favicon umjesto fa TODO !!!! */}
				{/* Place GTM container snippet directly in the head */}
			</head>
			<body>
				{/* Place GTM noscript iframe directly in the body */}
				<noscript>
					<iframe
						src="https://www.googletagmanager.com/ns.html?id=GTM-PR8P244L"
						height="0"
						width="0"
						style={{ display: 'none', visibility: 'hidden' }}></iframe>
				</noscript>
				<Navbar />
				<div>{children}</div>
				<Footer />
			</body>
		</HTML>
	)
}
